matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.2
      sudo: required

before_install:
  - bash ./common/install-imagemagick.sh
  - git submodule update --init --remote --merge --recursive

script:
  - ./Package-Builder/build-package.sh $TRAVIS_BUILD_DIR
  - bash ./common/coverage.sh

