codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "0...100"

  status:
    project:
      default: true

    patch:
      default: true

    changes:
      default: true

  ignore:
    - "Tests/*"
    - "Sources/CMagickWand/*"

comment:
  layout: "header"
  branches: null
  behavior: default
